# coding=utf-8
# ======================================
# File:     signal_parser.py
# Author:   Jackie PENG
# Contact:  jackie.pengzhao@gmail.com
# Created:  2025-07-10
# Desc:
#   Signal parser parses trading signals
# generated by strategies into trade
# orders.
# ======================================

